### ISSUE TITLE
Nested fluxo stores

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#20]
Sometimes you need that some internal attributes of your store behave like stores or collections and today Fluxo doesn't handle this use case well. If you set a store on some store's attribute its `toJSON` won't work correctly and you don't have the event bubbling.

I already created an extension of Fluxo's store to proof of concept on https://github.com/fluxo-js/fluxo-relational and it works great, but I really think we can fix these two issues aforementioned on the Fluxo's core, like done on my PoC.

We just can make some tweaks on de dependencies declaration with a more simple API using the native attributes parsers that we have today, like this:

``` jsx
class Comments extends Fluxo.CollectionStore {
  // ...
}

class Post extends Fluxo.ObjectStore {
  static defaults = {
    comments: []
  };
  static attributesParser = {
    comments: Fluxo.StoreAttribute(Comments)
  };
}
```

_in this case the comments attributes on post will be coerced on a `Comments` collection_

**Comment by sobrinho** [comment]
We could use something like that under the hood but a expressive public API is a must IMO, i.e.:

``` javascript
class Post extends Fluxo.ObjectStore {
  static relations = {
    comments: Comments
  }
}
```

We can do even better because that explicit dependency sucks (loading order would matters, Comments must be loaded before Post):

``` javascript
class Post extends Fluxo.ObjectStore {
  // we would use class name as string to avoid the need of a inflector
  static relations = {
    comments: 'Comments'
  };
}
```

And if we don't need to customize anything, we could sugar more:

``` javascript
class Post extends Fluxo.ObjectStore {
  // we would use class name as string to avoid the need of a inflector
  static relations = ['Comments', 'Categories'];
}
```

Makes sense?

**Comment by samuelsimoes** [comment]
About expressive relation's public API it also was my first thought, but I was thinking we don't need bring the concept of "relation" on itself like we are used to think on Rails, for example. IMO this feature it's all about store's attributes being casted to a fluxo store (and the proper Fluxo's behavior preparation), like any other casting (integer, date, moment.js and so on).

About usage with the class name for me no problems; about loading order I think we don't need worry about this since the current vibe on javascript is explicit require the dependencies of each module besides it's a safe precaution.

**Comment by sobrinho** [comment]
Although I'm not sure about calling it relations because it automatically infers that stores are models when they aren't.

We may came up with a new term like `substores` as we have `subsets`, but not sure about that name either.

**Comment by sobrinho** [comment]
Wrote the comment before github loaded yours, but it's the same thought.

Not sure about the `defaults` and the casting because it would be a tedious boilerplate and error prone (remove one and forget the other or write one and forget the another).

Any ideias?

**Comment by samuelsimoes** [comment]
So, the default array to `comments` attributes on my example would be if I want the store starting on the object construction. 

Like any other attribute on the actual attribute parser you can leave it null. It's only casted if you try update the attribute with a non null value.

**Comment by sobrinho** [comment]
Would be something like that?

``` javascript
Fluxo.StoreAttribute = function StoreAttribute (store) {
  return function (attrs) {
    return new store(attrs);
  };
};
```

**Comment by samuelsimoes** [comment]
The rough idea it is, but not so simple I think, because we need make some checks: 

1 current value is a store and users send a literal object (in this case update or replace the store with a new instance?)
2 current value is a store X and user pass a store Y (throw error because the different store?)

Besides that we also need to setup the event bubbling (on my PoC if you try a `post.data.author.setAttribute("name", "Fluxo")` the `post` store emits `author:change:name` event) and prepare the `toJSON`.

**Comment by samuelsimoes** [comment]
By the way, the main focus of issue is to prepare the Fluxo to handles well the attributes that are fluxo stores (event bubbling and toJSON). :)

**Comment by sobrinho** [comment]
I think that implementing specs to that without the real implementation yet (BDD) would help us :)

For example, that's clear to me:

``` javascript
post = new Post;

expect(post.comments).to.be.an.instance.of(Comments);
```

Although I'm not 100% sure about this one, I think it makes sense to `setAttribute` just instantiate another collection store:

``` javascript
let oldComments = post.comments;

post.setAttribute("comments", [{id: 1, comment: "cool"}]);

expect(post.comments).to.be.an.instance.of(Comments);
expect(post.comments).to.not.be(oldComments);
```

I can see some problems with it but given a good documentation, that would be clear.

After these specs, despite being not entirely related to the original issue, we could think about what need to be done on the core to make the PoC more resilient.

**Comment by samuelsimoes** [comment]
So, I guess that we can split this issue on two considerable problems:

1.Prepare Fluxo to deal with "store attributes".
2.Create the API to do the right casting job.

Main main concern on this issue is the "store attributes" with these two improvements:

1 - event bubbling with "children stores" to do things like this:

``` js
class Post extends Fluxo.ObjectStore {
  static computed = {
    hasNewComment: ["comments:add"]
  }

  hasNewComment () {
    return true;
  }

  markAsRead () {
    this.setAttribute("hasNewComment", false);
  }
}
```

2 - the correct `toJSON` output

``` js
let post = new Post(),
    comments = new Fluxo.CollectionStore([{ id: 20, content: "Hi!", author: "Samuel" }]);

post.setAttribute("posts", comments);

post.toJSON();
{
  cid: "FS:1",
  comments: {
    cid: "FS:2",
    stores: [
      { cid: "FS:3", id: 20, content: "Hi!", author: "Samuel" }
    ]
  }
}
```

We could create the second issue to discuss more focused each problem. 
I want start to code this one :point_up::grin:

**Comment by sobrinho** [comment]
About the type casting I was thinking in something like that:

``` javascript
class CollectionParser {
  constructor (collectionStore) {
    this.collectionStore = collectionStore;
  }

  default () {
    return new this.collectionStore;
  }

  parse (data) {
    return new this.collectionStore(data);
  }

  dump (collectionStore) {
    return collectionStore.toJSON();
  }
};

class Post extends Fluxo.Store {
  static attributeParsers = {
    comments: new CollectionParser(Comments)
  }
}
```

I'm thinking in parsers as protocol of:
- `default` which returns the default complex data object (we do not need default plain value because the `dump` will handle that)
- `parse` which receives the back-end/plain value and returns the complex data object
- `dump` which receives the complex data object and returns the value which will be sent to back-end and/or components.

Assuming that we have `Fluxo.Store.prototype.toJSON` and `Fluxo.CollectionStore.prototype.toJSON`, the store parser will be simple to implement.

About the event bubbling, create the other issue and I will write some ideas :see_no_evil:

**Comment by samuelsimoes** [comment]
I like the ideia of a more "robust parser", but I have some misgiving about the `default` behavior abiding in the parser since we already have the store `defaults`.

If we will use this issue to casting, we need to think about this parser usage with the two problems aforementioned:

**1 - current value is already a store and users send a literal object (in this case update or replace the store with a new instance?)**
_IMO we need to carefully think about this behavior because the developer can make some `setAttribute` on the child store and a parent `setAttribute("comments", [{...}])` can obliterate the child state._

**2 - current value is a store X and user make a `setAttribute` with a Y** 
I can't think on some use case to this "swapping store", but I think is safe we break this (until some use case appears) to prevent oddly behaviors.

**Comment by sobrinho** [comment]
Both cases seems to make sense to replace the store, just like this:

``` javascript
let oldComments = post.getAttribute("comments");

post.setAttribute("comments", [{id: 1}]);

expect(post.getAttribute("comments")).to.not.be(oldComments);
expect(post.getAttribute("comments")).to.be.an.instance.of(Comments);
```

``` javascript
let oldComments = post.getAttribute("comments"),
    newComments = new CommentsStore;

post.setAttribute("comments", newComments);

expect(post.getAttribute("comments")).to.not.be(oldComments);
expect(post.getAttribute("comments")).to.be(newComments);
```

I do not expect to mutate the current store in that case because I'm setting a new value which infers a new instance.

If I want to keep the same instance, that would be something like that:

``` javascript
post.get("comments").reset([{id: 1}]);
```

Although if you think on this behaviour, may be a little more difficult to implement a "destroy everything that is not present on the nested if it get replaced" but that's rare case and computed attributes may help to discover which one got deleted.

Following the principle we follow today on our systems, the record would be kept on the store with a flag instead of begin removed from there.

We need to decide that before go to `defaults` problem, :baby: :walking: hahahaahaha

**Comment by samuelsimoes** [comment]
Understood, my concern was on this example: imagine that Slack does a dumb pooling to fetch the chat and its messages are nested.

I click on the edit button on some message and the message becomes on the editing mode, if I take too long to edit my message on the next chat fetch my message will exit the edit mode and I will lost my edition.

Coding this example will be like this:

``` js
let chat = new Chat({ 
  name: "General", 
  messages: [{ id: 20, content: "Hi" }] 
});

let editingMessage = chat.data.messages.stores[0];

editingMessage.set({
  editing: true,
  newContent: editingMessage.data.content
});

$.get("/chats/1", (data) => {
  // data is { name: "General", messages: [{ id: 20, content: "Hello" }] }
  chat.setAttribute(data);
});
```

If the parser keep the child store instance and uses the `Fluxo.CollectionStore#setStores` (`setStores` actually does a smart hydration) this problem above won't happens.

**Comment by sobrinho** [comment]
I see, in that case the correct implementation would be:

``` javascript
$.get("/chats/1", (data) => {
  chat.get("messages").push(data);
});
```

I think that `push` is not on core yet but I have this method in one of my projects to deal with that exactly case which is push instead of replace the entire collection.

Note that if the dumb query does return already existing messages on the collection store, you would need to use `merge` instead of push (which I also have in one project to deal with that exactly case too).

Makes sense?

**Comment by samuelsimoes** [comment]
So, you say to do this:

``` js
$.get("/chats/1/messages", (data) => {
  chat.data.messages.setStores(data);
});
```

It in fact is an alternative to fix the example, so it may not be a big problem at all. Let's move on.

_About the merge behavior the collection's `setStores` actually does it (https://github.com/fluxo-js/fluxo/blob/master/src/fluxo.collection_store.js#L140-L159)._

**Comment by sobrinho** [comment]
Given that, we can write the following specs:
- `setAttribute` must replace the previous store if a store is given
- `setAttribute` must create a new store if a plain object is given

Probably we can do that simple doing that:

``` javascript
class CollectionParser {
  constructor (collectionStore) {
    if (!(collectionStore instanceof Fluxo.CollectionStore)) {
      throw `collectionStore must be a Fluxo.CollectionStore, ${collectionStore.constructor} given`;
    }

    this.collectionStore = collectionStore;
  }

  parse (data) {
    if (data instanceof this.collectionStore) {
      return data;
    }

    return new this.collectionStore(data);
  }

  dump (collectionStore) {
    return collectionStore.toJSON();
  }
}
```

``` javascript
class ObjectParser {
  constructor (objectStore) {
    if (!(objectStore instanceof Fluxo.ObjectStore)) {
      throw `objectStore must be a Fluxo.ObjectStore, ${collectionStore.constructor} given`;
    }

    if (objectStore instanceof Fluxo.CollectionStore) {
      throw 'objectStore must be a Fluxo.ObjectStore, if you want to cast a Fluxo.CollectionStore you must use Fluxo.CollectionParser instead';
    }

    this.objectStore = objectStore;
  }

  parse (data) {
    if (data instanceof this.objectStore) {
      return data;
    }

    return new this.objectStore(data);
  }

  dump (objectStore) {
    return objectStore.toJSON();
  }
}
```

Questions:
1. dump should be called if the value is falsey? That would allow us to dump an empty array or an empty object.
2. data must be validated on parse? Would make more sense to the store itself check the given data on constructor.

**Comment by samuelsimoes** [comment]
:+1: 

about the questions:

1 - IMO dump shouldn't be called when its value is falsy. This can leads to situation where I don't have default value to the casted value but my `toJSON` returns a value to an attribute that I didn't have defined (yet). So I find this behavior a little weird.

2 - Without doubt on the store's constructor :P

**Comment by sobrinho** [comment]
I think we may have an issue if a default value is not specified for a collection parser attribute because the component will receive a undefined instead of an empty array but we can handle that on the PoC latter (do not allowing not undefined, aka, requiring the default to be an empty array).

I think you can grab these two drafts above, write some specs and fix anything that need to be fixed :shipit: 

After that we can create a new issue for discussing about how we can deal with event bubbling to finish the PoC :+1:

**Comment by samuelsimoes** [comment]
I'm starting to think we need converge all these questions to this object. The casting, if it's required, the allowed types for this attribute, the default value, the way that it's dumped and the way that it's unsetted.

Something like this:

``` js
class Post {
  static attributes = {
    content: StringAttribute({ 
      required: true,
      default: "New Post"
    }),
    date: DateAttribute({ 
      required: true, 
      defaultValue: (new Date()) 
    })
  }
}
```

With this we implement the store parsing and rules in a breeze.

**Comment by sobrinho** [comment]
It's interesting because we ensure a strict type check but is bureaucratic and should be optional, small applications almost doesn't have any benefit of using it.

Assuming that is optional, I heavily agree on that solution, it's a mixed solution for casting, type checking and default values all in one.

Although I do not like the `required` idea because validations on front-end are often complex and duplicated from the back-end, which increases maintenance.

Besides that, we would need to think about how to expose these validation errors which lead us to think about i18n, custom validators, custom messages and so on.

And I would suggest a small change: use instantiated objects since it's easier for beginners to understand (as we see frequently on pairs) and implement new attribute types:

``` javascript
// Fluxo.Attribute would be an interface to have nicer error messages just like we do in ruby
// We can also use it to ensure that attributes on the store are in fact Fluxo.Attribute classes, double win
class MomentAttribute extends Fluxo.Attribute {
  parse (value) {
    return moment(value);
  }

  dump (value) {
    return value.toJSON();
  }
}

// getDefault would be the way to return the default value
// using a static property at all would be problematic due to mutation (like ary.push)
class CollectionStoreAttribute extends Fluxo.Attribute {
  parse (data) {
    return new this.options.collectionStore(data);
  }

  dump (collectionStore) {
    return collectionStore.toJSON();
  }

  getDefault () {
    return new this.options.collectionStore;
  }
}

class Post extends Fluxo.ObjectStore {
  static attributes = {
    title: new Fluxo.StringAttribute({
      defaultValue: "New Post"
    }),

    publishedAt: new MomentAttribute,

    categories: new Fluxo.CollectionStoreAttribute({
      collectionStore: CategoriesStore
    })
  }
}

post = new Post;
post.setAttribute("title", 1); // throws exception due to type check
post.setAttribute("published", true); // works as work today, no type check or anything like that
post.getAttribute("categories"); // returns an empty array since the CollectionStoreAttribute would be able to specify that
```

**Comment by samuelsimoes** [comment]
So, the `required` "validation" there is like what we have on the React, not a front-end validation, but the things that store's internally (for some reason) need, the contract.

I was using the "factory function" there because we could generate instances per store instance injecting the store on these attributes parsers, which can be very useful. With this one attribute parser instance per class model we can't do this.

The rest of things is like you said. :)

**Comment by sobrinho** [comment]
I'm still not sure about the required parameter but it may be useful, I need to see a real use case to understand if the cost values the benefits, more features = more things to worry on each new release.

About the factory function, I think it's a anti-pattern to access the store at all on the attribute parser, we may have issues of all sorts, i.e.: attribute parser order dependency, circular-dependencies, etc.

``` javascript
class Post {
  static attributes = {
    title: buildStringParser,
    createdAt: buildDateParser
  }
}

post = new Post({title: "foo", createdAt: "foo"});
```

Supposing that title parser needs the createdAt attribute casted, there is a problem because the order of the parsers isn't guaranteed.

Also, I don't see any real use case for a attribute parser access the store, they should be pure functions.

On my proposal you don't need the class at all, it's just a easier way to quickly understand a pure parser:

``` javascript
function parseMoment (value) {
  return moment(value);
}

function dumpMoment (moment) {
  return moment.toJSON();
}

class Post extends Fluxo.ObjectStore {
  static attributes = {
    publishedAt: { parse: parseMoment, dump: dumpMoment }
  }
}
```

Implementing then as pure functions would allow us (us you may read as the VM) to cache function calls to reduce parsing costs.

If the store is sent to the parser, would be complex to optimize that in the future.

**Comment by samuelsimoes** [comment]
Hmmm, understood, I also don't have any case of attribute parser accessing the store, so pure functions would work like charm.

The `required` feature could allows the store to has a strong contract, for example, we have a attribute that hold a collection store and our view layer is prepared to only deals with array, with you try nullify or instantiate the store without this, which is the "state of view layer", an exception will alert us, but I already don't know if we need such  "security level", as you said it increases the maintenance, so, get rid of it?

**Comment by sobrinho** [comment]
I would prefer to skip it for now to keep the implementation simple, we could work on that on the future :)

**Comment by samuelsimoes** [comment]
Okie dokie.

**Comment by samuelsimoes** [comment]
I think the rest of this issue was about the "attributes protocol", so let discuss this on the dedicated issue https://github.com/fluxo-js/fluxo/issues/26
